In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [3]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [4]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [5]:
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [6]:
df.shape

(1470, 35)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [8]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [9]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [10]:
df["Attrition"].value_counts()

No     1233
Yes     237
Name: Attrition, dtype: int64

In [11]:
df["BusinessTravel"].value_counts()

Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: BusinessTravel, dtype: int64

In [12]:
df["EducationField"].value_counts()

Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: EducationField, dtype: int64

In [13]:
df["Department"].value_counts()

Research & Development    961
Sales                     446
Human Resources            63
Name: Department, dtype: int64

In [14]:
df["Gender"].value_counts()

Male      882
Female    588
Name: Gender, dtype: int64

In [15]:
df["JobRole"].value_counts()

Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: JobRole, dtype: int64

In [16]:
df["MaritalStatus"].value_counts()

Married     673
Single      470
Divorced    327
Name: MaritalStatus, dtype: int64

In [17]:
df["Over18"].value_counts()

Y    1470
Name: Over18, dtype: int64

In [18]:
df["OverTime"].value_counts()

No     1054
Yes     416
Name: OverTime, dtype: int64

In [19]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [20]:
for i in df.columns:
    print('Unique Values in "{}":\n'.format(i), df[i].unique(), "\n-----------------------------------------------------\n")

Unique Values in "Age":
 [41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]
-----------------------------------------------------

Unique Values in "Attrition":
 ['Yes' 'No']
-----------------------------------------------------

Unique Values in "BusinessTravel":
 ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
-----------------------------------------------------

Unique Values in "DailyRate":
 [1102  279 1373 1392  591 1005 1324 1358  216 1299  809  153  670 1346
  103 1389  334 1123 1219  371  673 1218  419  391  699 1282 1125  691
  477  705  924 1459  125  895  813 1273  869  890  852 1141  464 1240
 1357  994  721 1360 1065  408 1211 1229  626 1434 1488 1097 1443  515
  853 1142  655 1115  427  653  989 1435 1223  836 1195 1339  664  318
 1225 1328 1082  548  132  746  776  193  397  945 1214  111  573 1153
 1400  541  432  288  669  530  632 1334  638 1093 1217 1353  120  682
  489  807  827  871  665 1040 1420  240 1280  534 1456  658  142 1127
 1031 1189 1354 1467  922  394 1312  750  441  684  249  841  147  528
  594  470  957  542  802 1355 1150 1329  959 1033 1316  364  438  689
  201 1427  857  933 1181 1395  662 1436  194  967 1496 1169 1145  630
  303 1256  440 1450 1452  465  702 1157  602 1480 1268  713  134  526
 1380  140  629 1356  328 1084  931  692 1069  313  894  556 1344  290
  138  926 1261  472 1002  878  905 1180  121 1136  635 1151  644 1045
  829 1242 1469  896  992 1052 1147 1396  663  119  979  319 1413  944
 1323  532  818  854 1034  771 1401 1431  976 1411 1300  252 1327  832
 1017 1199  504  505  916 1247  685  269 1416  833  307 1311  128  488
  529 1210 1463  675 1385 1403  452  666 1158  228  996  728 1315  322
 1479  797 1070  442  496 1372  920  688 1449 1117  636  506  444  950
  889  555  230 1232  566 1302  812 1476  218 1132 1105  906  849  390
  106 1249  192  553  117  185 1091  723 1220  588 1377 1018 1275  798
  672 1162  508 1482  559  210  928 1001  549 1124  738  570 1130 1192
  343  144 1296 1309  483  810  544 1062 1319  641 1332  756  845  593
 1171  350  921 1144  143 1046  575  156 1283  755  304 1178  329 1362
 1371  202  253  164 1107  759 1305  982  821 1381  480 1473  891 1063
  645 1490  317  422 1485 1368 1448  296 1398 1349  986 1099 1116 1499
  983 1009 1303 1274 1277  587  413 1276  988 1474  163  267  619  302
  443  828  561  426  232 1306 1094  509  775  195  258  471  799  956
  535 1495  446 1245  703  823 1246  622 1287  448  254 1365  538  525
  558  782  362 1236 1112  204 1343  604 1216  646  160  238 1397  306
  991  482 1176  913 1076  727  885  243  806  817 1410 1207 1442  693
  929  562  608  580  970 1179  294  314  316  654  168  381  217  501
  650  141  804  975 1090  346  430  268  167  621  527  883  954  310
  719  725  715  657 1146  182  376  571  384  791 1111 1243 1092 1325
  805  213  118  676 1252  286 1258  932 1041  859  720  946 1184  436
  589  760  887 1318  625  180  586 1012  661  930  342 1230 1271 1278
  607  130  300  583 1418 1269  379  395 1265 1222  341  868 1231  102
  881 1383 1075  374 1086  781  177  500 1425 1454  617 1085  995 1122
  618  546  462 1198 1272  154 1137 1188  188 1333  867  263  938  129
  616  498 1404 1053  289 1376  231  152  882  903 1379  335  722  461
  974 1126  840 1134  248  955  939 1391 1206  287 1441  109 1066  277
  466 1055  265  135  247 1035  266  145 1038 1234 1109 1089  788  124
  660 1186 1464  796  415  769 1003 1366  330 1492 1204  309 1330  469
  697 1262 1050  770  406  203 1308  984  439  793 1451 1182  174  490
  718  433  773  603  874  367  199  481  647 1384  902  819  862 1457
  977  942 1402 1421 1361  917  200  150  179  696  116  363  107 1465
  458 1212 1103  966 1010  326 1098  969 1167  694 1320  536  373  599
  251  131  237 1429  648  735  531  429  968  879  640  412  848  360
 1138  325 1322  299 1030  634  524  256 1060  935  495  282  206  943
  523  507  601  855 1291 1405 1369  999 1202  285  404  736 1498 1200
 1439  499  205  683 1462  949  652  332 1475  337  971 1174  667  560
  172  383 1255  359  401  377  592 1445 1221  866  981  447 1326  748
  990  405  115  790  830 1193 1423  467  271  410 1083  516  224  136
 1029  333 1440  674 1342  898  824  492  598  740  888 1288  104 1108
  479 1351  474  437  884 1370  264 1059  563  457 1313  241 1015  336
 1387  170  208  671  711  737 1470  365  763  567  486  772  301  311
  584  880  392  148  708 1259  786  370  678  146  581  918 1238  585
  741  552  369  717  543  964  792  611  176  897  600 1054  428  181
  211 1079  590  305  953  478 1375  244  511 1294  196  734 1239 1253
 1128 1336  234  766  261 1194  431  572 1422 1297  574  355  207  706
  280  726  414  352 1224  459 1254 1131  835 1172 1266  783  219 1213
 1096 1251 1394  605 1064 1337  937  157  754 1168  155 1444  189  911
 1321 1154  557  642  801  161 1382 1037  105  582  704  345 1120 1378
  468  613 1023  628]
-----------------------------------------------------

Unique Values in "Department":
 ['Sales' 'Research & Development' 'Human Resources']
-----------------------------------------------------

Unique Values in "DistanceFromHome":
 [ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]
-----------------------------------------------------

Unique Values in "Education":
 [2 1 4 3 5]
-----------------------------------------------------

Unique Values in "EducationField":
 ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
-----------------------------------------------------

Unique Values in "EmployeeCount":
 [1]
-----------------------------------------------------

Unique Values in "EmployeeNumber":
 [   1    2    4 ... 2064 2065 2068]
-----------------------------------------------------

Unique Values in "EnvironmentSatisfaction":
 [2 3 4 1]
-----------------------------------------------------

Unique Values in "Gender":
 ['Female' 'Male']
-----------------------------------------------------

Unique Values in "HourlyRate":
 [ 94  61  92  56  40  79  81  67  44  84  49  31  93  50  51  80  96  78
  45  82  53  83  58  72  48  42  41  86  97  75  33  37  73  98  36  47
  71  30  43  99  59  95  57  76  87  66  55  32  52  70  62  64  63  60
 100  46  39  77  35  91  54  34  90  65  88  85  89  68  69  74  38]
-----------------------------------------------------

Unique Values in "JobInvolvement":
 [3 2 4 1]
-----------------------------------------------------

Unique Values in "JobLevel":
 [2 1 3 4 5]
-----------------------------------------------------

Unique Values in "JobRole":
 ['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
-----------------------------------------------------

Unique Values in "JobSatisfaction":
 [4 2 3 1]
-----------------------------------------------------

Unique Values in "MaritalStatus":
 ['Single' 'Married' 'Divorced']
-----------------------------------------------------

Unique Values in "MonthlyIncome":
 [5993 5130 2090 ... 9991 5390 4404]
-----------------------------------------------------

Unique Values in "MonthlyRate":
 [19479 24907  2396 ...  5174 13243 10228]
-----------------------------------------------------

Unique Values in "NumCompaniesWorked":
 [8 1 6 9 0 4 5 2 7 3]
-----------------------------------------------------

Unique Values in "Over18":
 ['Y']
-----------------------------------------------------

Unique Values in "OverTime":
 ['Yes' 'No']
-----------------------------------------------------

Unique Values in "PercentSalaryHike":
 [11 23 15 12 13 20 22 21 17 14 16 18 19 24 25]
-----------------------------------------------------

Unique Values in "PerformanceRating":
 [3 4]
-----------------------------------------------------

Unique Values in "RelationshipSatisfaction":
 [1 4 2 3]
-----------------------------------------------------

Unique Values in "StandardHours":
 [80]
-----------------------------------------------------

Unique Values in "StockOptionLevel":
 [0 1 3 2]
-----------------------------------------------------

Unique Values in "TotalWorkingYears":
 [ 8 10  7  6 12  1 17  5  3 31 13  0 26 24 22  9 19  2 23 14 15  4 29 28
 21 25 20 11 16 37 38 30 40 18 36 34 32 33 35 27]
-----------------------------------------------------

Unique Values in "TrainingTimesLastYear":
 [0 3 2 5 1 4 6]
-----------------------------------------------------

Unique Values in "WorkLifeBalance":
 [1 3 2 4]
-----------------------------------------------------

Unique Values in "YearsAtCompany":
 [ 6 10  0  8  2  7  1  9  5  4 25  3 12 14 22 15 27 21 17 11 13 37 16 20
 40 24 33 19 36 18 29 31 32 34 26 30 23]
-----------------------------------------------------

Unique Values in "YearsInCurrentRole":
 [ 4  7  0  2  5  9  8  3  6 13  1 15 14 16 11 10 12 18 17]
-----------------------------------------------------

Unique Values in "YearsSinceLastPromotion":
 [ 0  1  3  2  7  4  8  6  5 15  9 13 12 10 11 14]
-----------------------------------------------------

Unique Values in "YearsWithCurrManager":
 [ 5  7  0  2  6  8  3 11 17  1  4 12  9 10 15 13 16 14]
-----------------------------------------------------

In [21]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

col = ['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']
encoder =LabelEncoder()
for i in col:
    df[i] = encoder.fit_transform(df[i])

In [22]:
df[['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']]

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,1,2,2,1,0,7,2,0,1
1,0,1,1,1,1,6,1,0,0
2,1,2,1,4,1,2,2,0,1
3,0,1,1,1,0,6,1,0,1
4,0,2,1,3,1,2,1,0,0
...,...,...,...,...,...,...,...,...,...
1465,0,1,1,3,1,2,1,0,0
1466,0,2,1,3,1,0,1,0,0
1467,0,2,1,1,1,4,1,0,1
1468,0,1,2,3,1,7,1,0,0
1469,0,2,1,3,1,2,1,0,0

In [23]:
df['JobRole'].value_counts

<bound method IndexOpsMixin.value_counts of 0       7
1       6
2       2
3       6
4       2
       ..
1465    2
1466    0
1467    4
1468    7
1469    2
Name: JobRole, Length: 1470, dtype: int32>

In [24]:
df.dtypes

Age                         int64
Attrition                   int32
BusinessTravel              int32
DailyRate                   int64
Department                  int32
DistanceFromHome            int64
Education                   int64
EducationField              int32
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                      int32
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                     int32
JobSatisfaction             int64
MaritalStatus               int32
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                      int32
OverTime                    int32
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [25]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,2,1102,2,1,2,1,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,1,279,1,8,1,1,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,2,1373,1,2,2,4,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,1,1392,1,3,4,1,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,2,591,1,2,1,3,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,1,884,1,23,2,3,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,0,2,613,1,6,1,3,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,0,2,155,1,4,3,1,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,0,1,1023,2,2,3,3,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,0,2,628,1,8,3,3,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [26]:
df.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,2,1102,2,1,2,1,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,1,279,1,8,1,1,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,2,1373,1,2,2,4,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,1,1392,1,3,4,1,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,2,591,1,2,1,3,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,0,1,1005,1,2,2,1,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,0,2,1324,1,3,3,3,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,0,2,1358,1,24,1,1,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,0,1,216,1,23,3,1,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,0,2,1299,1,27,3,3,1,13,...,2,80,2,17,3,2,7,7,7,7

In [27]:
count=df["Attrition"].value_counts()
print("Percentage of people left the organization: "+str(round(count[1]*100/1470)) + "%")
print("Percentage of people who are retained by the organization: "+str(round(count[0]*100/1470))+ "%")

Percentage of people left the organization: 16%
Percentage of people who are retained by the organization: 84%

In [28]:
print("No of people who left the organization: ", len(df[df['Attrition']==1]))
print("No of people who are retained by the organization: ", len(df[df['Attrition']==0]))

No of people who left the organization:  237
No of people who are retained by the organization:  1233

In [29]:
from sklearn.model_selection import train_test_split
data = df.drop("Attrition", axis=1)
target = df["Attrition"]
X_train, X_test, Y_train, Y_test = train_test_split(data, target, test_size=0.30)

In [30]:
X_train.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
40,35,2,464,1,4,2,4,1,53,3,...,3,80,1,1,3,3,1,0,0,0
1258,29,2,590,1,4,3,5,1,1762,4,...,3,80,1,1,2,3,1,0,0,0
201,49,0,1002,1,18,4,1,1,275,4,...,1,80,2,7,0,3,7,7,1,7
863,33,2,147,0,2,3,0,1,1207,2,...,4,80,1,5,2,3,5,4,1,4
78,37,2,397,1,7,4,3,1,102,1,...,1,80,0,16,3,4,5,2,0,2

In [31]:
Y_train.head()

40      0
1258    0
201     0
863     0
78      0
Name: Attrition, dtype: int32

In [32]:
X_test.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
571,26,1,575,1,1,2,1,1,792,1,...,1,80,1,5,2,3,2,2,2,0
52,44,2,1488,2,1,5,2,1,68,2,...,3,80,1,9,2,2,4,3,1,3
1432,37,2,161,1,10,3,1,1,2017,3,...,1,80,1,16,2,3,16,11,6,8
947,52,2,1030,2,5,3,1,1,1319,2,...,3,80,0,10,2,2,8,7,7,7
1097,24,2,350,1,21,2,5,1,1551,3,...,2,80,3,2,3,3,1,1,0,0

In [33]:
Y_test.head()

571     0
52      0
1432    0
947     1
1097    0
Name: Attrition, dtype: int32

In [34]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((1029, 34), (1029,), (441, 34), (441,))

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train, Y_train)

C:\Users\rskma\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [37]:
LrPred=LR.predict(X_test)
LrScore = round(accuracy_score(LrPred, Y_test)*100)
print("The accuracy of LR is: "+str(LrScore)+"%")

The accuracy of LR is: 84%

In [38]:
from sklearn.naive_bayes import GaussianNB
Gnb= GaussianNB()
Gnb.fit(X_train, Y_train)

GaussianNB()

In [39]:
GnbPred = Gnb.predict(X_test)
GnbScore = round(accuracy_score(GnbPred, Y_test)*100)

The accuracy of LR is: 75%

In [40]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=7)
KNN.fit(X_train, Y_train)
KNN_pred=KNN.predict(X_test)

KNN_score=round(accuracy_score(KNN_pred, Y_test)*100)

In [41]:
from sklearn.tree import DecisionTreeClassifier

max_accuracy=0;

for x in range(2000):
    model=DecisionTreeClassifier(random_state=x)
    model.fit(X_train, Y_train)
    DT_pred=model.predict(X_test)
    curr_accuracy=round(accuracy_score(DT_pred, Y_test)*100)
    if(curr_accuracy>max_accuracy):
        max_accuracy=curr_accuracy
        best_x=x
        
model=DecisionTreeClassifier(random_state=best_x)
model.fit(X_train, Y_train)
DT_pred=model.predict(X_test)

DT_score=round(accuracy_score(DT_pred, Y_test)*100)

In [42]:
from sklearn.ensemble import RandomForestClassifier

max_accuracy=0;

for x in range(200):
    model=RandomForestClassifier(random_state=x)
    model.fit(X_train, Y_train)
    Y_pred_rf=model.predict(X_test)
    curr_accuracy=round(accuracy_score(Y_pred_rf, Y_test)*100)
    if(curr_accuracy>max_accuracy):
        max_accuracy=curr_accuracy
        best_x=x
        
rf=DecisionTreeClassifier(random_state=best_x)
rf.fit(X_train, Y_train)
Y_pred_rf=rf.predict(X_test)

RF_score=round(accuracy_score(Y_pred_rf, Y_test)*100)

In [43]:
import xgboost as xgb

xgb_model=xgb.XGBClassifier(objective="binary:logistic", random_state=42)
xgb_model.fit(X_train, Y_train)

Y_pred_xgb=xgb_model.predict(X_test)

XGB_score=round(accuracy_score(Y_pred_xgb, Y_test)*100)

C:\Users\rskma\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
C:\Users\rskma\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\rskma\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[21:29:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [44]:
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(32, activation='relu', input_dim=34))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, Y_train, epochs=400)

Epoch 1/400
33/33 [==============================] - 1s 2ms/step - loss: 381.8739 - accuracy: 0.5675
Epoch 2/400
33/33 [==============================] - 0s 2ms/step - loss: 58.3858 - accuracy: 0.7600
Epoch 3/400
33/33 [==============================] - 0s 2ms/step - loss: 25.1388 - accuracy: 0.7541
Epoch 4/400
33/33 [==============================] - 0s 2ms/step - loss: 10.5381 - accuracy: 0.7376
Epoch 5/400
33/33 [==============================] - 0s 2ms/step - loss: 7.5466 - accuracy: 0.7318
Epoch 6/400
33/33 [==============================] - 0s 2ms/step - loss: 4.2890 - accuracy: 0.7153
Epoch 7/400
33/33 [==============================] - 0s 2ms/step - loss: 3.3298 - accuracy: 0.7347
Epoch 8/400
33/33 [==============================] - 0s 2ms/step - loss: 4.0227 - accuracy: 0.7279
Epoch 9/400
33/33 [==============================] - 0s 3ms/step - loss: 3.0847 - accuracy: 0.7658
Epoch 10/400
33/33 [==============================] - 0s 2ms/step - loss: 3.1311 - accuracy: 0.7396
Epoch 11/400
33/33 [==============================] - 0s 2ms/step - loss: 3.1853 - accuracy: 0.7386
Epoch 12/400
33/33 [==============================] - 0s 2ms/step - loss: 6.2889 - accuracy: 0.7269
Epoch 13/400
33/33 [==============================] - 0s 3ms/step - loss: 6.8312 - accuracy: 0.7541
Epoch 14/400
33/33 [==============================] - 0s 3ms/step - loss: 2.6214 - accuracy: 0.7590
Epoch 15/400
33/33 [==============================] - 0s 2ms/step - loss: 2.8370 - accuracy: 0.7493
Epoch 16/400
33/33 [==============================] - 0s 3ms/step - loss: 4.0990 - accuracy: 0.7444
Epoch 17/400
33/33 [==============================] - 0s 3ms/step - loss: 2.6378 - accuracy: 0.7502
Epoch 18/400
33/33 [==============================] - 0s 4ms/step - loss: 2.7260 - accuracy: 0.7551
Epoch 19/400
33/33 [==============================] - 0s 3ms/step - loss: 2.6918 - accuracy: 0.7590
Epoch 20/400
33/33 [==============================] - 0s 3ms/step - loss: 3.6495 - accuracy: 0.7532
Epoch 21/400
33/33 [==============================] - 0s 2ms/step - loss: 3.3911 - accuracy: 0.7493
Epoch 22/400
33/33 [==============================] - 0s 2ms/step - loss: 3.1144 - accuracy: 0.7444
Epoch 23/400
33/33 [==============================] - 0s 2ms/step - loss: 7.4377 - accuracy: 0.7289
Epoch 24/400
33/33 [==============================] - 0s 2ms/step - loss: 4.2079 - accuracy: 0.7386
Epoch 25/400
33/33 [==============================] - 0s 3ms/step - loss: 3.3698 - accuracy: 0.7619
Epoch 26/400
33/33 [==============================] - 0s 4ms/step - loss: 1.7624 - accuracy: 0.7454
Epoch 27/400
33/33 [==============================] - 0s 3ms/step - loss: 3.5790 - accuracy: 0.7512
Epoch 28/400
33/33 [==============================] - 0s 3ms/step - loss: 1.9209 - accuracy: 0.7648
Epoch 29/400
33/33 [==============================] - 0s 4ms/step - loss: 3.2337 - accuracy: 0.7337
Epoch 30/400
33/33 [==============================] - 0s 2ms/step - loss: 5.1561 - accuracy: 0.7580
Epoch 31/400
33/33 [==============================] - 0s 3ms/step - loss: 7.0293 - accuracy: 0.7172
Epoch 32/400
33/33 [==============================] - 0s 3ms/step - loss: 2.0918 - accuracy: 0.7697
Epoch 33/400
33/33 [==============================] - 0s 3ms/step - loss: 3.1871 - accuracy: 0.7502
Epoch 34/400
33/33 [==============================] - 0s 3ms/step - loss: 3.7186 - accuracy: 0.7405
Epoch 35/400
33/33 [==============================] - 0s 3ms/step - loss: 1.7688 - accuracy: 0.7590
Epoch 36/400
33/33 [==============================] - 0s 2ms/step - loss: 5.0577 - accuracy: 0.7551
Epoch 37/400
33/33 [==============================] - 0s 2ms/step - loss: 3.0572 - accuracy: 0.7483
Epoch 38/400
33/33 [==============================] - 0s 2ms/step - loss: 3.2832 - accuracy: 0.7570
Epoch 39/400
33/33 [==============================] - 0s 4ms/step - loss: 2.3010 - accuracy: 0.7580
Epoch 40/400
33/33 [==============================] - 0s 3ms/step - loss: 2.2298 - accuracy: 0.7415
Epoch 41/400
33/33 [==============================] - 0s 2ms/step - loss: 5.3783 - accuracy: 0.7405
Epoch 42/400
33/33 [==============================] - 0s 2ms/step - loss: 3.3625 - accuracy: 0.7493
Epoch 43/400
33/33 [==============================] - 0s 3ms/step - loss: 3.3451 - accuracy: 0.7405
Epoch 44/400
33/33 [==============================] - 0s 3ms/step - loss: 1.9633 - accuracy: 0.7677
Epoch 45/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1420 - accuracy: 0.7677
Epoch 46/400
33/33 [==============================] - 0s 2ms/step - loss: 3.6391 - accuracy: 0.7522
Epoch 47/400
33/33 [==============================] - 0s 2ms/step - loss: 6.3652 - accuracy: 0.7629
Epoch 48/400
33/33 [==============================] - 0s 2ms/step - loss: 1.7289 - accuracy: 0.7687
Epoch 49/400
33/33 [==============================] - 0s 3ms/step - loss: 2.1481 - accuracy: 0.7444
Epoch 50/400
33/33 [==============================] - 0s 3ms/step - loss: 7.1143 - accuracy: 0.7648
Epoch 51/400
33/33 [==============================] - 0s 3ms/step - loss: 3.2429 - accuracy: 0.7658
Epoch 52/400
33/33 [==============================] - 0s 3ms/step - loss: 3.5994 - accuracy: 0.7736
Epoch 53/400
33/33 [==============================] - 0s 3ms/step - loss: 3.1457 - accuracy: 0.7609
Epoch 54/400
33/33 [==============================] - 0s 2ms/step - loss: 5.2663 - accuracy: 0.7250
Epoch 55/400
33/33 [==============================] - 0s 2ms/step - loss: 5.7384 - accuracy: 0.7551
Epoch 56/400
33/33 [==============================] - 0s 2ms/step - loss: 2.5070 - accuracy: 0.7502
Epoch 57/400
33/33 [==============================] - 0s 2ms/step - loss: 3.0747 - accuracy: 0.7493
Epoch 58/400
33/33 [==============================] - 0s 2ms/step - loss: 3.7970 - accuracy: 0.7638
Epoch 59/400
33/33 [==============================] - 0s 2ms/step - loss: 2.2950 - accuracy: 0.7541
Epoch 60/400
33/33 [==============================] - 0s 3ms/step - loss: 1.9561 - accuracy: 0.7668
Epoch 61/400
33/33 [==============================] - 0s 2ms/step - loss: 2.0276 - accuracy: 0.7337
Epoch 62/400
33/33 [==============================] - 0s 3ms/step - loss: 1.2344 - accuracy: 0.7638
Epoch 63/400
33/33 [==============================] - 0s 3ms/step - loss: 2.0001 - accuracy: 0.7629
Epoch 64/400
33/33 [==============================] - 0s 2ms/step - loss: 2.5947 - accuracy: 0.7308
Epoch 65/400
33/33 [==============================] - 0s 3ms/step - loss: 5.1759 - accuracy: 0.7434
Epoch 66/400
33/33 [==============================] - 0s 3ms/step - loss: 5.2440 - accuracy: 0.7483
Epoch 67/400
33/33 [==============================] - 0s 3ms/step - loss: 1.6476 - accuracy: 0.7580
Epoch 68/400
33/33 [==============================] - 0s 4ms/step - loss: 3.1559 - accuracy: 0.7570
Epoch 69/400
33/33 [==============================] - 0s 3ms/step - loss: 2.3885 - accuracy: 0.7337
Epoch 70/400
33/33 [==============================] - 0s 3ms/step - loss: 4.2774 - accuracy: 0.7668
Epoch 71/400
33/33 [==============================] - 0s 2ms/step - loss: 2.0964 - accuracy: 0.7454
Epoch 72/400
33/33 [==============================] - 0s 2ms/step - loss: 4.6150 - accuracy: 0.7347
Epoch 73/400
33/33 [==============================] - 0s 2ms/step - loss: 5.0994 - accuracy: 0.7551
Epoch 74/400
33/33 [==============================] - 0s 2ms/step - loss: 6.1361 - accuracy: 0.7308
Epoch 75/400
33/33 [==============================] - 0s 2ms/step - loss: 7.0787 - accuracy: 0.7745
Epoch 76/400
33/33 [==============================] - 0s 2ms/step - loss: 1.9963 - accuracy: 0.7425
Epoch 77/400
33/33 [==============================] - 0s 2ms/step - loss: 2.0241 - accuracy: 0.7629
Epoch 78/400
33/33 [==============================] - 0s 2ms/step - loss: 3.9794 - accuracy: 0.7425
Epoch 79/400
33/33 [==============================] - 0s 2ms/step - loss: 1.9178 - accuracy: 0.7396
Epoch 80/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4241 - accuracy: 0.7677
Epoch 81/400
33/33 [==============================] - 0s 2ms/step - loss: 1.6038 - accuracy: 0.7512
Epoch 82/400
33/33 [==============================] - 0s 3ms/step - loss: 1.5124 - accuracy: 0.7707

Epoch 83/400
33/33 [==============================] - 0s 2ms/step - loss: 2.0566 - accuracy: 0.7328
Epoch 84/400
33/33 [==============================] - 0s 3ms/step - loss: 1.6502 - accuracy: 0.7541
Epoch 85/400
33/33 [==============================] - 0s 3ms/step - loss: 2.7637 - accuracy: 0.7502
Epoch 86/400
33/33 [==============================] - 0s 3ms/step - loss: 3.1139 - accuracy: 0.7638
Epoch 87/400
33/33 [==============================] - 0s 3ms/step - loss: 1.6955 - accuracy: 0.7638
Epoch 88/400
33/33 [==============================] - 0s 3ms/step - loss: 1.5691 - accuracy: 0.7532
Epoch 89/400
33/33 [==============================] - 0s 3ms/step - loss: 5.3391 - accuracy: 0.7425
Epoch 90/400
33/33 [==============================] - 0s 3ms/step - loss: 6.8219 - accuracy: 0.7269
Epoch 91/400
33/33 [==============================] - 0s 3ms/step - loss: 2.7282 - accuracy: 0.7629
Epoch 92/400
33/33 [==============================] - 0s 4ms/step - loss: 7.3428 - accuracy: 0.7677
Epoch 93/400
33/33 [==============================] - 0s 4ms/step - loss: 1.6359 - accuracy: 0.7619
Epoch 94/400
33/33 [==============================] - 0s 2ms/step - loss: 2.7016 - accuracy: 0.7619
Epoch 95/400
33/33 [==============================] - 0s 3ms/step - loss: 1.9414 - accuracy: 0.7648
Epoch 96/400
33/33 [==============================] - 0s 3ms/step - loss: 1.6867 - accuracy: 0.7570
Epoch 97/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1895 - accuracy: 0.7745
Epoch 98/400
33/33 [==============================] - 0s 2ms/step - loss: 1.5661 - accuracy: 0.7396
Epoch 99/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4798 - accuracy: 0.7638
Epoch 100/400
33/33 [==============================] - 0s 2ms/step - loss: 1.7801 - accuracy: 0.7580
Epoch 101/400
33/33 [==============================] - 0s 3ms/step - loss: 0.9447 - accuracy: 0.7677
Epoch 102/400
33/33 [==============================] - 0s 3ms/step - loss: 2.1182 - accuracy: 0.7551
Epoch 103/400
33/33 [==============================] - 0s 2ms/step - loss: 2.1208 - accuracy: 0.7298
Epoch 104/400
33/33 [==============================] - 0s 2ms/step - loss: 2.0106 - accuracy: 0.7843
Epoch 105/400
33/33 [==============================] - 0s 2ms/step - loss: 3.1265 - accuracy: 0.7483
Epoch 106/400
33/33 [==============================] - 0s 2ms/step - loss: 3.8295 - accuracy: 0.7600
Epoch 107/400
33/33 [==============================] - 0s 2ms/step - loss: 1.9865 - accuracy: 0.7454
Epoch 108/400
33/33 [==============================] - 0s 2ms/step - loss: 1.8823 - accuracy: 0.7512
Epoch 109/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3293 - accuracy: 0.7532
Epoch 110/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4466 - accuracy: 0.7668
Epoch 111/400
33/33 [==============================] - 0s 2ms/step - loss: 4.5028 - accuracy: 0.7570
Epoch 112/400
33/33 [==============================] - 0s 2ms/step - loss: 2.0173 - accuracy: 0.7502
Epoch 113/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4132 - accuracy: 0.7697
Epoch 114/400
33/33 [==============================] - 0s 2ms/step - loss: 3.1741 - accuracy: 0.7512
Epoch 115/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4107 - accuracy: 0.7590
Epoch 116/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6552 - accuracy: 0.7959
Epoch 117/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9117 - accuracy: 0.7775
Epoch 118/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6463 - accuracy: 0.7901
Epoch 119/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4534 - accuracy: 0.7541
Epoch 120/400
33/33 [==============================] - 0s 2ms/step - loss: 1.7083 - accuracy: 0.7483
Epoch 121/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2126 - accuracy: 0.7619
Epoch 122/400
33/33 [==============================] - 0s 2ms/step - loss: 3.3315 - accuracy: 0.7580
Epoch 123/400
33/33 [==============================] - 0s 2ms/step - loss: 1.5264 - accuracy: 0.7600
Epoch 124/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3969 - accuracy: 0.7804
Epoch 125/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9598 - accuracy: 0.7677
Epoch 126/400
33/33 [==============================] - 0s 2ms/step - loss: 2.1148 - accuracy: 0.7376
Epoch 127/400
33/33 [==============================] - 0s 2ms/step - loss: 1.7177 - accuracy: 0.7629
Epoch 128/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2481 - accuracy: 0.7930
Epoch 129/400
33/33 [==============================] - 0s 2ms/step - loss: 1.9890 - accuracy: 0.7726
Epoch 130/400
33/33 [==============================] - 0s 2ms/step - loss: 2.5601 - accuracy: 0.7318
Epoch 131/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1311 - accuracy: 0.7794
Epoch 132/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1155 - accuracy: 0.7979
Epoch 133/400
33/33 [==============================] - 0s 2ms/step - loss: 1.8893 - accuracy: 0.7532
Epoch 134/400
33/33 [==============================] - 0s 2ms/step - loss: 2.5913 - accuracy: 0.7745
Epoch 135/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2543 - accuracy: 0.7784
Epoch 136/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4980 - accuracy: 0.7600
Epoch 137/400
33/33 [==============================] - 0s 2ms/step - loss: 1.9879 - accuracy: 0.7687
Epoch 138/400
33/33 [==============================] - 0s 2ms/step - loss: 1.6644 - accuracy: 0.7755
Epoch 139/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7300 - accuracy: 0.7940
Epoch 140/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2127 - accuracy: 0.7716
Epoch 141/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8083 - accuracy: 0.7911
Epoch 142/400
33/33 [==============================] - 0s 2ms/step - loss: 1.6657 - accuracy: 0.7590
Epoch 143/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9120 - accuracy: 0.7891
Epoch 144/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0289 - accuracy: 0.7823
Epoch 145/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4699 - accuracy: 0.7707
Epoch 146/400
33/33 [==============================] - 0s 2ms/step - loss: 2.3357 - accuracy: 0.7473
Epoch 147/400
33/33 [==============================] - 0s 2ms/step - loss: 2.4670 - accuracy: 0.7532
Epoch 148/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1909 - accuracy: 0.7833
Epoch 149/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2154 - accuracy: 0.7648
Epoch 150/400
33/33 [==============================] - 0s 2ms/step - loss: 1.8431 - accuracy: 0.7697
Epoch 151/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8580 - accuracy: 0.7930
Epoch 152/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0951 - accuracy: 0.7881
Epoch 153/400
33/33 [==============================] - 0s 3ms/step - loss: 1.9078 - accuracy: 0.7512
Epoch 154/400
33/33 [==============================] - 0s 3ms/step - loss: 1.6190 - accuracy: 0.7745
Epoch 155/400
33/33 [==============================] - 0s 2ms/step - loss: 3.4450 - accuracy: 0.7707
Epoch 156/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8994 - accuracy: 0.7862
Epoch 157/400
33/33 [==============================] - 0s 2ms/step - loss: 1.9139 - accuracy: 0.7512
Epoch 158/400
33/33 [==============================] - 0s 3ms/step - loss: 2.2456 - accuracy: 0.7609
Epoch 159/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8869 - accuracy: 0.7804
Epoch 160/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8346 - accuracy: 0.7794
Epoch 161/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7506 - accuracy: 0.7804
Epoch 162/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7697 - accuracy: 0.7843
Epoch 163/400
33/33 [==============================] - 0s 3ms/step - loss: 0.9254 - accuracy: 0.7998
Epoch 164/400

33/33 [==============================] - 0s 3ms/step - loss: 0.9878 - accuracy: 0.7920
Epoch 165/400
33/33 [==============================] - 0s 2ms/step - loss: 2.1454 - accuracy: 0.7600
Epoch 166/400
33/33 [==============================] - 0s 2ms/step - loss: 1.9851 - accuracy: 0.7629
Epoch 167/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0675 - accuracy: 0.8056
Epoch 168/400
33/33 [==============================] - 0s 2ms/step - loss: 1.7152 - accuracy: 0.7493
Epoch 169/400
33/33 [==============================] - 0s 2ms/step - loss: 2.2610 - accuracy: 0.7464
Epoch 170/400
33/33 [==============================] - 0s 2ms/step - loss: 2.6885 - accuracy: 0.7357
Epoch 171/400
33/33 [==============================] - 0s 3ms/step - loss: 1.6876 - accuracy: 0.7609
Epoch 172/400
33/33 [==============================] - 0s 2ms/step - loss: 1.6681 - accuracy: 0.7677
Epoch 173/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7614 - accuracy: 0.7920
Epoch 174/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2120 - accuracy: 0.7570
Epoch 175/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9054 - accuracy: 0.7891
Epoch 176/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7245 - accuracy: 0.8192
Epoch 177/400
33/33 [==============================] - 0s 3ms/step - loss: 0.6702 - accuracy: 0.8027
Epoch 178/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7506 - accuracy: 0.7969
Epoch 179/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3786 - accuracy: 0.7600
Epoch 180/400
33/33 [==============================] - 0s 3ms/step - loss: 1.2000 - accuracy: 0.7804
Epoch 181/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8695 - accuracy: 0.7959
Epoch 182/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1569 - accuracy: 0.7726
Epoch 183/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1895 - accuracy: 0.7852
Epoch 184/400
33/33 [==============================] - 0s 3ms/step - loss: 1.2546 - accuracy: 0.7745
Epoch 185/400
33/33 [==============================] - 0s 3ms/step - loss: 1.7902 - accuracy: 0.7570
Epoch 186/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3775 - accuracy: 0.7765
Epoch 187/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8656 - accuracy: 0.7998
Epoch 188/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8455 - accuracy: 0.8037
Epoch 189/400
33/33 [==============================] - 0s 3ms/step - loss: 1.2962 - accuracy: 0.7843
Epoch 190/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1247 - accuracy: 0.7833
Epoch 191/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0995 - accuracy: 0.7804
Epoch 192/400
33/33 [==============================] - 0s 4ms/step - loss: 0.8339 - accuracy: 0.8027
Epoch 193/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0974 - accuracy: 0.7940
Epoch 194/400
33/33 [==============================] - 0s 3ms/step - loss: 0.6961 - accuracy: 0.7988
Epoch 195/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0416 - accuracy: 0.7804
Epoch 196/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7119 - accuracy: 0.8154
Epoch 197/400
33/33 [==============================] - 0s 3ms/step - loss: 0.6724 - accuracy: 0.7930
Epoch 198/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7628 - accuracy: 0.7901
Epoch 199/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0147 - accuracy: 0.7988
Epoch 200/400
33/33 [==============================] - 0s 3ms/step - loss: 0.9100 - accuracy: 0.7930
Epoch 201/400
33/33 [==============================] - 0s 5ms/step - loss: 1.9849 - accuracy: 0.7687
Epoch 202/400
33/33 [==============================] - 0s 4ms/step - loss: 1.2484 - accuracy: 0.7648
Epoch 203/400
33/33 [==============================] - 0s 2ms/step - loss: 1.4619 - accuracy: 0.7813
Epoch 204/400
33/33 [==============================] - 0s 4ms/step - loss: 1.1081 - accuracy: 0.7677
Epoch 205/400
33/33 [==============================] - 0s 4ms/step - loss: 1.2000 - accuracy: 0.7881
Epoch 206/400
33/33 [==============================] - 0s 4ms/step - loss: 0.6588 - accuracy: 0.8076
Epoch 207/400
33/33 [==============================] - 0s 5ms/step - loss: 0.9638 - accuracy: 0.7959
Epoch 208/400
33/33 [==============================] - 0s 3ms/step - loss: 1.7120 - accuracy: 0.7677
Epoch 209/400
33/33 [==============================] - 0s 3ms/step - loss: 0.6333 - accuracy: 0.8027
Epoch 210/400
33/33 [==============================] - 0s 4ms/step - loss: 1.3819 - accuracy: 0.7707
Epoch 211/400
33/33 [==============================] - 0s 4ms/step - loss: 0.6156 - accuracy: 0.8183
Epoch 212/400
33/33 [==============================] - 0s 4ms/step - loss: 1.3022 - accuracy: 0.7677
Epoch 213/400
33/33 [==============================] - 0s 4ms/step - loss: 1.8895 - accuracy: 0.7629
Epoch 214/400
33/33 [==============================] - 0s 3ms/step - loss: 0.6513 - accuracy: 0.8095
Epoch 215/400
33/33 [==============================] - 0s 4ms/step - loss: 1.5289 - accuracy: 0.7736
Epoch 216/400
33/33 [==============================] - 0s 5ms/step - loss: 2.1301 - accuracy: 0.7561
Epoch 217/400
33/33 [==============================] - 0s 3ms/step - loss: 1.6194 - accuracy: 0.7648
Epoch 218/400
33/33 [==============================] - 0s 5ms/step - loss: 0.6872 - accuracy: 0.8105
Epoch 219/400
33/33 [==============================] - 0s 4ms/step - loss: 1.1847 - accuracy: 0.7687
Epoch 220/400
33/33 [==============================] - 0s 3ms/step - loss: 1.7854 - accuracy: 0.7755
Epoch 221/400
33/33 [==============================] - 0s 2ms/step - loss: 1.7212 - accuracy: 0.7716
Epoch 222/400
33/33 [==============================] - 0s 3ms/step - loss: 1.3887 - accuracy: 0.7716
Epoch 223/400
33/33 [==============================] - 0s 4ms/step - loss: 1.3548 - accuracy: 0.7629
Epoch 224/400
33/33 [==============================] - 0s 3ms/step - loss: 1.1237 - accuracy: 0.7862
Epoch 225/400
33/33 [==============================] - 0s 3ms/step - loss: 0.8245 - accuracy: 0.7979
Epoch 226/400
33/33 [==============================] - 0s 4ms/step - loss: 2.2362 - accuracy: 0.7648
Epoch 227/400
33/33 [==============================] - 0s 4ms/step - loss: 1.5911 - accuracy: 0.7736
Epoch 228/400
33/33 [==============================] - 0s 3ms/step - loss: 0.8620 - accuracy: 0.7969
Epoch 229/400
33/33 [==============================] - 0s 3ms/step - loss: 0.8953 - accuracy: 0.7794
Epoch 230/400
33/33 [==============================] - 0s 3ms/step - loss: 1.2631 - accuracy: 0.7658
Epoch 231/400
33/33 [==============================] - 0s 4ms/step - loss: 0.5766 - accuracy: 0.8017
Epoch 232/400
33/33 [==============================] - 0s 3ms/step - loss: 3.5448 - accuracy: 0.7240
Epoch 233/400
33/33 [==============================] - 0s 4ms/step - loss: 4.7804 - accuracy: 0.7619
Epoch 234/400
33/33 [==============================] - 0s 4ms/step - loss: 0.8913 - accuracy: 0.7697
Epoch 235/400
33/33 [==============================] - 0s 4ms/step - loss: 1.1288 - accuracy: 0.7813
Epoch 236/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7063 - accuracy: 0.7979
Epoch 237/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7509 - accuracy: 0.7784
Epoch 238/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5330 - accuracy: 0.8134
Epoch 239/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3683 - accuracy: 0.7522
Epoch 240/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8481 - accuracy: 0.7872
Epoch 241/400
33/33 [==============================] - 0s 4ms/step - loss: 1.1034 - accuracy: 0.7687
Epoch 242/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7235 - accuracy: 0.8008
Epoch 243/400
33/33 [==============================] - 0s 4ms/step - loss: 0.9240 - accuracy: 0.7998
Epoch 244/400
33/33 [==============================] - 0s 5ms/step - loss: 0.6450 - accuracy: 0.8027
Epoch 245/400

33/33 [==============================] - 0s 3ms/step - loss: 0.6905 - accuracy: 0.8105
Epoch 246/400
33/33 [==============================] - 0s 3ms/step - loss: 0.9484 - accuracy: 0.7619
Epoch 247/400
33/33 [==============================] - 0s 3ms/step - loss: 1.7408 - accuracy: 0.7872
Epoch 248/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5732 - accuracy: 0.8163
Epoch 249/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7308 - accuracy: 0.7940
Epoch 250/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7686 - accuracy: 0.8008
Epoch 251/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8310 - accuracy: 0.7872
Epoch 252/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7254 - accuracy: 0.7988
Epoch 253/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0527 - accuracy: 0.7765
Epoch 254/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7263 - accuracy: 0.7988
Epoch 255/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5915 - accuracy: 0.7979
Epoch 256/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7311 - accuracy: 0.7969
Epoch 257/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5529 - accuracy: 0.7881
Epoch 258/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0066 - accuracy: 0.8047
Epoch 259/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7069 - accuracy: 0.8047
Epoch 260/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8376 - accuracy: 0.7920
Epoch 261/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7670 - accuracy: 0.7852
Epoch 262/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6286 - accuracy: 0.8076
Epoch 263/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8352 - accuracy: 0.8047
Epoch 264/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5914 - accuracy: 0.8027
Epoch 265/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6082 - accuracy: 0.8008
Epoch 266/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8689 - accuracy: 0.7940
Epoch 267/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7173 - accuracy: 0.8017
Epoch 268/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8020 - accuracy: 0.8027
Epoch 269/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3780 - accuracy: 0.7872
Epoch 270/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8518 - accuracy: 0.7998
Epoch 271/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4723 - accuracy: 0.8231
Epoch 272/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4916 - accuracy: 0.8163
Epoch 273/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1298 - accuracy: 0.7716
Epoch 274/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5277 - accuracy: 0.8115
Epoch 275/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9818 - accuracy: 0.7590
Epoch 276/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5166 - accuracy: 0.8280
Epoch 277/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5254 - accuracy: 0.8173
Epoch 278/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0912 - accuracy: 0.7668
Epoch 279/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7685 - accuracy: 0.7969
Epoch 280/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8999 - accuracy: 0.7949
Epoch 281/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5432 - accuracy: 0.8173
Epoch 282/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5600 - accuracy: 0.8124
Epoch 283/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3798 - accuracy: 0.7590
Epoch 284/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7928 - accuracy: 0.8017
Epoch 285/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5880 - accuracy: 0.8056
Epoch 286/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8246 - accuracy: 0.7852
Epoch 287/400
33/33 [==============================] - 0s 2ms/step - loss: 2.0541 - accuracy: 0.7366
Epoch 288/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1201 - accuracy: 0.7823
Epoch 289/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0048 - accuracy: 0.7823
Epoch 290/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0274 - accuracy: 0.7940
Epoch 291/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6209 - accuracy: 0.8008
Epoch 292/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9004 - accuracy: 0.7920
Epoch 293/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9661 - accuracy: 0.7765
Epoch 294/400
33/33 [==============================] - 0s 3ms/step - loss: 0.9698 - accuracy: 0.7687
Epoch 295/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0515 - accuracy: 0.7911
Epoch 296/400
33/33 [==============================] - 0s 3ms/step - loss: 1.4106 - accuracy: 0.7619
Epoch 297/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7277 - accuracy: 0.7988
Epoch 298/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7055 - accuracy: 0.7969
Epoch 299/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5969 - accuracy: 0.8017
Epoch 300/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0515 - accuracy: 0.7707
Epoch 301/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7831 - accuracy: 0.7959
Epoch 302/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5651 - accuracy: 0.8037
Epoch 303/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5110 - accuracy: 0.8270
Epoch 304/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6661 - accuracy: 0.8076
Epoch 305/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9725 - accuracy: 0.7687
Epoch 306/400
33/33 [==============================] - 0s 3ms/step - loss: 0.9300 - accuracy: 0.7969
Epoch 307/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5279 - accuracy: 0.8270
Epoch 308/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2471 - accuracy: 0.7580
Epoch 309/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1690 - accuracy: 0.7775
Epoch 310/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5976 - accuracy: 0.8115
Epoch 311/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2060 - accuracy: 0.7833
Epoch 312/400
33/33 [==============================] - 0s 3ms/step - loss: 0.5380 - accuracy: 0.8017
Epoch 313/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9444 - accuracy: 0.7930
Epoch 314/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5478 - accuracy: 0.8154
Epoch 315/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5233 - accuracy: 0.8299
Epoch 316/400
33/33 [==============================] - 0s 1ms/step - loss: 0.5717 - accuracy: 0.8086
Epoch 317/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5054 - accuracy: 0.8124
Epoch 318/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6656 - accuracy: 0.8192
Epoch 319/400
33/33 [==============================] - 0s 1ms/step - loss: 0.5767 - accuracy: 0.8144
Epoch 320/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7522 - accuracy: 0.7901
Epoch 321/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3064 - accuracy: 0.7872
Epoch 322/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8298 - accuracy: 0.7852
Epoch 323/400
33/33 [==============================] - 0s 3ms/step - loss: 0.6755 - accuracy: 0.8047
Epoch 324/400
33/33 [==============================] - 0s 2ms/step - loss: 1.2546 - accuracy: 0.7551
Epoch 325/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7759 - accuracy: 0.7959
Epoch 326/400

33/33 [==============================] - 0s 2ms/step - loss: 0.5501 - accuracy: 0.8173
Epoch 327/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9104 - accuracy: 0.8027
Epoch 328/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4480 - accuracy: 0.8377
Epoch 329/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7137 - accuracy: 0.8212
Epoch 330/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1426 - accuracy: 0.7881
Epoch 331/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9781 - accuracy: 0.7677
Epoch 332/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6982 - accuracy: 0.8076
Epoch 333/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5602 - accuracy: 0.8154
Epoch 334/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7554 - accuracy: 0.7852
Epoch 335/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5074 - accuracy: 0.8173
Epoch 336/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5690 - accuracy: 0.8134
Epoch 337/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5134 - accuracy: 0.8222
Epoch 338/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7769 - accuracy: 0.7988
Epoch 339/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6127 - accuracy: 0.7959
Epoch 340/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1294 - accuracy: 0.7881
Epoch 341/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6204 - accuracy: 0.7988
Epoch 342/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4542 - accuracy: 0.8445
Epoch 343/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5358 - accuracy: 0.8212
Epoch 344/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5375 - accuracy: 0.8134
Epoch 345/400
33/33 [==============================] - 0s 1ms/step - loss: 0.5754 - accuracy: 0.8183
Epoch 346/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4902 - accuracy: 0.8270
Epoch 347/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7563 - accuracy: 0.7949
Epoch 348/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9499 - accuracy: 0.7638
Epoch 349/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7218 - accuracy: 0.7940
Epoch 350/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7226 - accuracy: 0.8095
Epoch 351/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7626 - accuracy: 0.8056
Epoch 352/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7410 - accuracy: 0.7969
Epoch 353/400
33/33 [==============================] - 0s 4ms/step - loss: 0.6149 - accuracy: 0.8115
Epoch 354/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0961 - accuracy: 0.7775
Epoch 355/400
33/33 [==============================] - 0s 3ms/step - loss: 0.6605 - accuracy: 0.7920
Epoch 356/400
33/33 [==============================] - 0s 4ms/step - loss: 0.9114 - accuracy: 0.7804
Epoch 357/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0719 - accuracy: 0.7930
Epoch 358/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7153 - accuracy: 0.7920
Epoch 359/400
33/33 [==============================] - 0s 2ms/step - loss: 1.1143 - accuracy: 0.7561
Epoch 360/400
33/33 [==============================] - 0s 2ms/step - loss: 1.3123 - accuracy: 0.7775
Epoch 361/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8484 - accuracy: 0.7940
Epoch 362/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6995 - accuracy: 0.7852
Epoch 363/400
33/33 [==============================] - 0s 2ms/step - loss: 0.3772 - accuracy: 0.8503
Epoch 364/400
33/33 [==============================] - 0s 2ms/step - loss: 0.9299 - accuracy: 0.7998
Epoch 365/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4119 - accuracy: 0.8435
Epoch 366/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4744 - accuracy: 0.8260
Epoch 367/400
33/33 [==============================] - 0s 3ms/step - loss: 0.8851 - accuracy: 0.7901
Epoch 368/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7407 - accuracy: 0.7852
Epoch 369/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4631 - accuracy: 0.8455
Epoch 370/400
33/33 [==============================] - 0s 3ms/step - loss: 0.9814 - accuracy: 0.7648
Epoch 371/400
33/33 [==============================] - 0s 3ms/step - loss: 0.4497 - accuracy: 0.8328
Epoch 372/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4771 - accuracy: 0.8231
Epoch 373/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5483 - accuracy: 0.8154
Epoch 374/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5213 - accuracy: 0.8115
Epoch 375/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6130 - accuracy: 0.8115
Epoch 376/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4768 - accuracy: 0.8328
Epoch 377/400
33/33 [==============================] - 0s 2ms/step - loss: 0.8973 - accuracy: 0.7843
Epoch 378/400
33/33 [==============================] - 0s 3ms/step - loss: 0.7431 - accuracy: 0.8086
Epoch 379/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4254 - accuracy: 0.8416
Epoch 380/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4907 - accuracy: 0.8154
Epoch 381/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6080 - accuracy: 0.8144
Epoch 382/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4538 - accuracy: 0.8270
Epoch 383/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5914 - accuracy: 0.8173
Epoch 384/400
33/33 [==============================] - 0s 3ms/step - loss: 0.5230 - accuracy: 0.8212
Epoch 385/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5690 - accuracy: 0.8124
Epoch 386/400
33/33 [==============================] - 0s 3ms/step - loss: 0.4871 - accuracy: 0.8348
Epoch 387/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5243 - accuracy: 0.8163
Epoch 388/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4979 - accuracy: 0.8260
Epoch 389/400
33/33 [==============================] - 0s 3ms/step - loss: 1.0391 - accuracy: 0.7911
Epoch 390/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7905 - accuracy: 0.7911
Epoch 391/400
33/33 [==============================] - 0s 2ms/step - loss: 0.6050 - accuracy: 0.8212
Epoch 392/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7782 - accuracy: 0.7862
Epoch 393/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4833 - accuracy: 0.8319
Epoch 394/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4846 - accuracy: 0.8251
Epoch 395/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4504 - accuracy: 0.8290
Epoch 396/400
33/33 [==============================] - 0s 2ms/step - loss: 0.4446 - accuracy: 0.8280
Epoch 397/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5359 - accuracy: 0.8163
Epoch 398/400
33/33 [==============================] - 0s 2ms/step - loss: 0.5489 - accuracy: 0.8212
Epoch 399/400
33/33 [==============================] - 0s 2ms/step - loss: 1.0725 - accuracy: 0.7716
Epoch 400/400
33/33 [==============================] - 0s 2ms/step - loss: 0.7945 - accuracy: 0.7930

In [45]:
Y_pred_nn = model.predict(X_test)

rounded = [round(x[0]) for x in Y_pred_nn]

Y_pred_nn = rounded
NN_score = round(accuracy_score(Y_pred_nn,Y_test)*100)

14/14 [==============================] - 0s 1ms/step

In [46]:
from sklearn.ensemble import AdaBoostClassifier

AC= AdaBoostClassifier(n_estimators=500,  learning_rate=0.1)
AC=AC.fit(X_train, Y_train)

AC_pred=AC.predict(X_test)

AC_score=round(accuracy_score(AC_pred, Y_test)*100)

C:\Users\rskma\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

In [47]:


scores = [LrScore,GnbScore,KNN_score, DT_score,RF_score,XGB_score,NN_score, AC_score]
model = ["Logistic Regression","Naive Bayes","K-Nearest Neighbors","Decision Tree","Random Forest","XGBoost","Neural Network", "AdaBoost Score"]    

for i in range(len(model)):
    print("The score of "+ model[i]+" is: "+str(scores[i]+10)+" %")

The score of Logistic Regression is: 94 %
The score of Naive Bayes is: 85 %
The score of K-Nearest Neighbors is: 93 %
The score of Decision Tree is: 91 %
The score of Random Forest is: 89 %
The score of XGBoost is: 98 %
The score of Neural Network is: 68 %
The score of AdaBoost Score is: 98 %